/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gymequippments.view;

import com.gymequipments.util.Validate;
import com.gymequippments.comtroller.algorithms.BinarySearch;
import com.gymequippments.comtroller.algorithms.InsertionSort;
import com.gymequippments.comtroller.algorithms.MergeSort;
import com.gymequippments.comtroller.algorithms.SelectionSort;
import com.gymequippments.model.gymequippmentsmodel;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//import 


/**
 *
 * @author SHUBHAM BHATTA
 */
public class gymequippmentsIs extends javax.swing.JFrame {
 
    private java.awt.CardLayout frameCardLayout;
    private java.awt.CardLayout homepanelcardLayout;
    private List<gymequippmentsmodel> euiplist;

    /**
     * Creates new form gymequippmentsIs
     */
    public gymequippmentsIs() {
        initComponents();
        frameLayout();
        homePanelLayout();
        initializedata();
        
    }
    
    private void initializedata(){
        euiplist = new ArrayList<>();
      
        registergymequip(new gymequippmentsmodel ("KTM1234","TREADMILL","255","panasonic","cardio","PTSE2","use to weightloss"));
        registergymequip(new gymequippmentsmodel ("KTM8888","CYCLE","230","NITRO","STRENGTH","POPTE2","to pump muscle"));
        registergymequip(new gymequippmentsmodel ("KTM4567","DUMBELL","210","PREDITOR","POWER LIFT","PITPR5"," muscle growth"));
        registergymequip(new gymequippmentsmodel ("KTM9876","BARBELL","185","HINDWARE","STRENGTH","POLTE2"," muscle growth"));
        registergymequip(new gymequippmentsmodel ("KTM7777","LATSPULLDOWN","230","LG","STRENGTH","PTTK6"," muscle growth"));
        
    }
        private void registergymequip(gymequippmentsmodel gym){
        euiplist.add(gym);
        DefaultTableModel model = (DefaultTableModel)tableGymEquipments .getModel();
        model.addRow(new Object[]{
        gym.getID(), gym.getName(), gym.getWeight(), gym.getBrand(), gym.getCategory(), gym.getModel(),gym.getUse()
});

    }
    
    private void frameLayout(){
        frameCardLayout= new CardLayout();
        getContentPane().setLayout(frameCardLayout);
        getContentPane().add(loginPanel,"loginPanel");
        getContentPane().add(mainpanel,"mainPanel");
        
        showPanels("loginPanel");
    }
    private void showPanels(String panel){
        frameCardLayout.show(getContentPane(),panel);
        
    }
    
    private void homePanelLayout(){
        homepanelcardLayout= new CardLayout();
        homePageMidPanel.setLayout(homepanelcardLayout);
        homePageMidPanel.add(adminPanel,"adminpanel");
        homePageMidPanel.add(homePanel,"homepanel");
        homePageMidPanel.add(aboutUsPanel, "aboutuspanel");
        
        showNewPanels("homepanel");
    }
    private void showNewPanels(String panel){
        homepanelcardLayout.show(homePageMidPanel, panel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        aboutusButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        homePageMidPanel = new javax.swing.JPanel();
        adminPanel = new javax.swing.JPanel();
        scrollPanelTable = new javax.swing.JScrollPane();
        tableGymEquipments = new javax.swing.JTable();
        VariablesPanel = new javax.swing.JPanel();
        idlabel = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        brandlabel = new javax.swing.JLabel();
        categorylabel = new javax.swing.JLabel();
        modelNolabel = new javax.swing.JLabel();
        useLabel = new javax.swing.JLabel();
        addbutton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        IdTextField = new javax.swing.JTextField();
        weightTextField = new javax.swing.JTextField();
        BrandTextField = new javax.swing.JTextField();
        modelNoTextfield = new javax.swing.JTextField();
        UseTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        categoryField = new javax.swing.JTextField();
        searchpanel = new javax.swing.JPanel();
        searchStudentLabel = new javax.swing.JLabel();
        SearchTextField = new javax.swing.JTextField();
        dropdownpanel = new javax.swing.JPanel();
        sortdropdown = new javax.swing.JComboBox<>();
        shortbytextfield = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();
        hometitlepanel = new javax.swing.JPanel();
        homelabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        homemidPanel = new javax.swing.JPanel();
        image1Panel = new javax.swing.JLabel();
        image1Text = new javax.swing.JLabel();
        image2 = new javax.swing.JLabel();
        image2Text = new javax.swing.JLabel();
        aboutUsPanel = new javax.swing.JPanel();
        aboutUsHeadPanel = new javax.swing.JPanel();
        aboutUslabel = new javax.swing.JLabel();
        labellogo = new javax.swing.JLabel();
        anoutUsMidPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        aboutusfotterPanel = new javax.swing.JPanel();
        twitterlogo = new javax.swing.JLabel();
        fabebooklogo = new javax.swing.JLabel();
        callIconLabel = new javax.swing.JLabel();
        mailAdressicon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        headlinePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginImage = new javax.swing.JLabel();
        textUserName = new javax.swing.JTextField();
        textPasscode = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();

        mainpanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(112, 88, 124), 3, true));

        aboutusButton.setText("ABOUT US");
        aboutusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutusButtonMouseClicked(evt);
            }
        });

        homeButton.setText("HOME");
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
        });

        adminButton.setText("ADMIN");
        adminButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminButtonMouseClicked(evt);
            }
        });
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gymequipments/resources/gym.png"))); // NOI18N

        jButton2.setText("LOG OUT");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aboutusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(aboutusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrollPanelTable.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(153, 153, 153)));

        tableGymEquipments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Weight", "Brand", "Category", "Model No.", "Use"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPanelTable.setViewportView(tableGymEquipments);
        if (tableGymEquipments.getColumnModel().getColumnCount() > 0) {
            tableGymEquipments.getColumnModel().getColumn(0).setMinWidth(100);
            tableGymEquipments.getColumnModel().getColumn(0).setPreferredWidth(100);
            tableGymEquipments.getColumnModel().getColumn(0).setMaxWidth(100);
            tableGymEquipments.getColumnModel().getColumn(1).setMinWidth(200);
            tableGymEquipments.getColumnModel().getColumn(1).setPreferredWidth(200);
            tableGymEquipments.getColumnModel().getColumn(1).setMaxWidth(200);
            tableGymEquipments.getColumnModel().getColumn(2).setMinWidth(100);
            tableGymEquipments.getColumnModel().getColumn(2).setPreferredWidth(100);
            tableGymEquipments.getColumnModel().getColumn(2).setMaxWidth(100);
            tableGymEquipments.getColumnModel().getColumn(3).setMinWidth(150);
            tableGymEquipments.getColumnModel().getColumn(3).setPreferredWidth(150);
            tableGymEquipments.getColumnModel().getColumn(3).setMaxWidth(150);
            tableGymEquipments.getColumnModel().getColumn(4).setMinWidth(150);
            tableGymEquipments.getColumnModel().getColumn(4).setPreferredWidth(150);
            tableGymEquipments.getColumnModel().getColumn(4).setMaxWidth(150);
            tableGymEquipments.getColumnModel().getColumn(5).setMinWidth(100);
            tableGymEquipments.getColumnModel().getColumn(5).setPreferredWidth(100);
            tableGymEquipments.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        VariablesPanel.setBackground(new java.awt.Color(112, 89, 124));
        VariablesPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(153, 153, 153)));

        idlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idlabel.setForeground(new java.awt.Color(255, 255, 255));
        idlabel.setText("ID:");

        namelabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namelabel.setForeground(new java.awt.Color(255, 255, 255));
        namelabel.setText("NAME:");

        weightLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        weightLabel.setForeground(new java.awt.Color(255, 255, 255));
        weightLabel.setText("WEIGHT:");

        brandlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        brandlabel.setForeground(new java.awt.Color(255, 255, 255));
        brandlabel.setText("BRAND:");

        categorylabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        categorylabel.setForeground(new java.awt.Color(255, 255, 255));
        categorylabel.setText("CATEGORY:");

        modelNolabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        modelNolabel.setForeground(new java.awt.Color(255, 255, 255));
        modelNolabel.setText("MODEL NO:");

        useLabel.setBackground(new java.awt.Color(255, 255, 255));
        useLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        useLabel.setForeground(new java.awt.Color(255, 255, 255));
        useLabel.setText("USE:");

        addbutton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addbutton.setText("ADD");
        addbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        addbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbuttonMouseClicked(evt);
            }
        });
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        IdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdTextFieldActionPerformed(evt);
            }
        });

        weightTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightTextFieldActionPerformed(evt);
            }
        });

        modelNoTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNoTextfieldActionPerformed(evt);
            }
        });

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        searchpanel.setBackground(new java.awt.Color(112, 88, 124));
        searchpanel.setForeground(new java.awt.Color(255, 255, 255));

        searchStudentLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        searchStudentLabel.setForeground(new java.awt.Color(255, 255, 255));
        searchStudentLabel.setText("search ID");
        searchStudentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchStudentLabelMouseClicked(evt);
            }
        });

        SearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchpanelLayout = new javax.swing.GroupLayout(searchpanel);
        searchpanel.setLayout(searchpanelLayout);
        searchpanelLayout.setHorizontalGroup(
            searchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchStudentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
        searchpanelLayout.setVerticalGroup(
            searchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        dropdownpanel.setBackground(new java.awt.Color(112, 89, 124));

        sortdropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Name", "Brand" }));
        sortdropdown.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 88, 124)));
        sortdropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortdropdownActionPerformed(evt);
            }
        });

        shortbytextfield.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        shortbytextfield.setForeground(new java.awt.Color(255, 255, 255));
        shortbytextfield.setText("short by");

        javax.swing.GroupLayout dropdownpanelLayout = new javax.swing.GroupLayout(dropdownpanel);
        dropdownpanel.setLayout(dropdownpanelLayout);
        dropdownpanelLayout.setHorizontalGroup(
            dropdownpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropdownpanelLayout.createSequentialGroup()
                .addGroup(dropdownpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dropdownpanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(sortdropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dropdownpanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(shortbytextfield)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        dropdownpanelLayout.setVerticalGroup(
            dropdownpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dropdownpanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(shortbytextfield)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(sortdropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout VariablesPanelLayout = new javax.swing.GroupLayout(VariablesPanel);
        VariablesPanel.setLayout(VariablesPanelLayout);
        VariablesPanelLayout.setHorizontalGroup(
            VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VariablesPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VariablesPanelLayout.createSequentialGroup()
                        .addComponent(useLabel)
                        .addGap(18, 18, 18)
                        .addComponent(UseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VariablesPanelLayout.createSequentialGroup()
                        .addGroup(VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VariablesPanelLayout.createSequentialGroup()
                                .addComponent(idlabel)
                                .addGap(18, 18, 18)
                                .addComponent(IdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(VariablesPanelLayout.createSequentialGroup()
                                .addComponent(brandlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BrandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(VariablesPanelLayout.createSequentialGroup()
                                .addComponent(namelabel)
                                .addGap(18, 18, 18)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(VariablesPanelLayout.createSequentialGroup()
                                .addComponent(categorylabel)
                                .addGap(18, 18, 18)
                                .addGroup(VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VariablesPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(weightLabel)
                        .addGap(18, 18, 18)
                        .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VariablesPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modelNolabel)
                            .addGroup(VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(VariablesPanelLayout.createSequentialGroup()
                                .addComponent(modelNoTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dropdownpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(searchpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        VariablesPanelLayout.setVerticalGroup(
            VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VariablesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VariablesPanelLayout.createSequentialGroup()
                        .addGroup(VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idlabel)
                            .addComponent(namelabel)
                            .addComponent(weightLabel)
                            .addComponent(IdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(186, 186, 186)
                        .addGroup(VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(useLabel)))
                    .addGroup(VariablesPanelLayout.createSequentialGroup()
                        .addGroup(VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(VariablesPanelLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(categorylabel)
                                    .addComponent(BrandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(brandlabel)
                                    .addComponent(modelNolabel)
                                    .addComponent(modelNoTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(VariablesPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(dropdownpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VariablesPanelLayout.createSequentialGroup()
                                .addGroup(VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(VariablesPanelLayout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(VariablesPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(searchpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanelTable, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(VariablesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VariablesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout homePageMidPanelLayout = new javax.swing.GroupLayout(homePageMidPanel);
        homePageMidPanel.setLayout(homePageMidPanelLayout);
        homePageMidPanelLayout.setHorizontalGroup(
            homePageMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageMidPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(adminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        homePageMidPanelLayout.setVerticalGroup(
            homePageMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageMidPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(adminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(homePageMidPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homePageMidPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        homePanel.setBackground(new java.awt.Color(112, 88, 124));
        homePanel.setPreferredSize(new java.awt.Dimension(1200, 800));

        hometitlepanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 12, 1, new java.awt.Color(153, 153, 153)));

        homelabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        homelabel.setForeground(new java.awt.Color(112, 88, 124));
        homelabel.setText("\n\" Healthier body with premium equipment that’s designed to maximize your results\"  ");

        javax.swing.GroupLayout hometitlepanelLayout = new javax.swing.GroupLayout(hometitlepanel);
        hometitlepanel.setLayout(hometitlepanelLayout);
        hometitlepanelLayout.setHorizontalGroup(
            hometitlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hometitlepanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(homelabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1169, Short.MAX_VALUE)
                .addContainerGap())
        );
        hometitlepanelLayout.setVerticalGroup(
            hometitlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hometitlepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        image1Panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gymequipments/resources/equipment (1).png"))); // NOI18N

        image1Text.setFont(new java.awt.Font("Segoe UI Symbol", 3, 36)); // NOI18N
        image1Text.setForeground(new java.awt.Color(112, 88, 124));
        image1Text.setText("<html>\" The complete bench of hundered <br>of strength and functional exercise \"</html.");

        image2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gymequipments/resources/cycling.png"))); // NOI18N

        image2Text.setFont(new java.awt.Font("Segoe UI Symbol", 3, 36)); // NOI18N
        image2Text.setForeground(new java.awt.Color(112, 88, 124));
        image2Text.setText("\"CYCLE YOUR STRENGTH\"");

        javax.swing.GroupLayout homemidPanelLayout = new javax.swing.GroupLayout(homemidPanel);
        homemidPanel.setLayout(homemidPanelLayout);
        homemidPanelLayout.setHorizontalGroup(
            homemidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homemidPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(homemidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(homemidPanelLayout.createSequentialGroup()
                        .addComponent(image1Panel)
                        .addGap(67, 67, 67)
                        .addComponent(image1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homemidPanelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(image2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(image2)))
                .addContainerGap(416, Short.MAX_VALUE))
        );
        homemidPanelLayout.setVerticalGroup(
            homemidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homemidPanelLayout.createSequentialGroup()
                .addGroup(homemidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homemidPanelLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(image1Panel))
                    .addGroup(homemidPanelLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(image1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(homemidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homemidPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(image2)
                        .addGap(224, 224, 224))
                    .addGroup(homemidPanelLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(image2Text)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jScrollPane1.setViewportView(homemidPanel);

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hometitlepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addComponent(hometitlepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                .addContainerGap())
        );

        aboutUsHeadPanel.setBackground(new java.awt.Color(112, 88, 124));
        aboutUsHeadPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(153, 153, 153)));
        aboutUsHeadPanel.setForeground(new java.awt.Color(255, 255, 255));

        aboutUslabel.setBackground(new java.awt.Color(112, 88, 124));
        aboutUslabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        aboutUslabel.setForeground(new java.awt.Color(255, 255, 255));
        aboutUslabel.setText("ABOUT US");

        labellogo.setForeground(new java.awt.Color(255, 255, 255));
        labellogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gymequipments/resources/information (1).png"))); // NOI18N

        javax.swing.GroupLayout aboutUsHeadPanelLayout = new javax.swing.GroupLayout(aboutUsHeadPanel);
        aboutUsHeadPanel.setLayout(aboutUsHeadPanelLayout);
        aboutUsHeadPanelLayout.setHorizontalGroup(
            aboutUsHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutUsHeadPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(labellogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aboutUslabel)
                .addContainerGap(736, Short.MAX_VALUE))
        );
        aboutUsHeadPanelLayout.setVerticalGroup(
            aboutUsHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutUsHeadPanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(aboutUsHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutUsHeadPanelLayout.createSequentialGroup()
                        .addComponent(labellogo)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutUsHeadPanelLayout.createSequentialGroup()
                        .addComponent(aboutUslabel)
                        .addGap(22, 22, 22))))
        );

        anoutUsMidPanel.setBackground(new java.awt.Color(255, 255, 255));
        anoutUsMidPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 5, 8, 5, new java.awt.Color(112, 88, 124)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(112, 88, 124));
        jLabel5.setText("<html>From 2006, The golden era of body-building Giratee fitness started building innovative advanced equipments<br>Giratee fitness containing  professional gym and fitness solution<br> understand that achieving your fitness goals requires the right tools. That’s why we offer a wide range of premium gym equipment, including strength training machines, cardio equipment, free weights, and accessories—all engineered for performance, durability, and innovation. Whether you’re setting up a home gym or managing a commercial fitness center, we’re here to meet your unique needs.</html>");

        javax.swing.GroupLayout anoutUsMidPanelLayout = new javax.swing.GroupLayout(anoutUsMidPanel);
        anoutUsMidPanel.setLayout(anoutUsMidPanelLayout);
        anoutUsMidPanelLayout.setHorizontalGroup(
            anoutUsMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anoutUsMidPanelLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        anoutUsMidPanelLayout.setVerticalGroup(
            anoutUsMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anoutUsMidPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        aboutusfotterPanel.setBackground(new java.awt.Color(112, 88, 124));
        aboutusfotterPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(153, 153, 153)));
        aboutusfotterPanel.setForeground(new java.awt.Color(153, 153, 153));

        twitterlogo.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        twitterlogo.setForeground(new java.awt.Color(255, 255, 255));
        twitterlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gymequipments/resources/twitter (1).png"))); // NOI18N
        twitterlogo.setText("@GRATEE");

        fabebooklogo.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        fabebooklogo.setForeground(new java.awt.Color(255, 255, 255));
        fabebooklogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gymequipments/resources/facebook.png"))); // NOI18N
        fabebooklogo.setText("@GIRATEE");

        callIconLabel.setFont(new java.awt.Font("Segoe UI Symbol", 3, 14)); // NOI18N
        callIconLabel.setForeground(new java.awt.Color(255, 255, 255));
        callIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gymequipments/resources/phone-call.png"))); // NOI18N
        callIconLabel.setText("+9779847392354");

        mailAdressicon.setFont(new java.awt.Font("Segoe UI Symbol", 3, 14)); // NOI18N
        mailAdressicon.setForeground(new java.awt.Color(255, 255, 255));
        mailAdressicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gymequipments/resources/email.png"))); // NOI18N
        mailAdressicon.setText("Girate69@gmail.com");

        javax.swing.GroupLayout aboutusfotterPanelLayout = new javax.swing.GroupLayout(aboutusfotterPanel);
        aboutusfotterPanel.setLayout(aboutusfotterPanelLayout);
        aboutusfotterPanelLayout.setHorizontalGroup(
            aboutusfotterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutusfotterPanelLayout.createSequentialGroup()
                .addGroup(aboutusfotterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(twitterlogo)
                    .addComponent(fabebooklogo))
                .addGap(30, 30, 30)
                .addGroup(aboutusfotterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(callIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailAdressicon))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        aboutusfotterPanelLayout.setVerticalGroup(
            aboutusfotterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutusfotterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutusfotterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twitterlogo)
                    .addComponent(callIconLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aboutusfotterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fabebooklogo)
                    .addComponent(mailAdressicon))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(112, 88, 124)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(112, 88, 124));
        jLabel1.setText("<html>We believe that fitness is more than just a lifestyle; it’s a commitment to becoming the best version of yourself.<br> Our mission is to empower individuals and communities by providing superior gym equipment that inspires and supports their fitness ambitions.</html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout aboutUsPanelLayout = new javax.swing.GroupLayout(aboutUsPanel);
        aboutUsPanel.setLayout(aboutUsPanelLayout);
        aboutUsPanelLayout.setHorizontalGroup(
            aboutUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutUsPanelLayout.createSequentialGroup()
                .addGroup(aboutUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aboutUsHeadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(aboutUsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(aboutusfotterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(aboutUsPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(anoutUsMidPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutUsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299))
        );
        aboutUsPanelLayout.setVerticalGroup(
            aboutUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutUsPanelLayout.createSequentialGroup()
                .addComponent(aboutUsHeadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(anoutUsMidPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(aboutusfotterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        loginPanel.setBackground(new java.awt.Color(232, 232, 232));

        headlinePanel.setBackground(new java.awt.Color(112, 88, 124));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gymequipments/resources/exercise.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GYM  EQUIPMENTS  INFORMATION  SYSTEM");

        javax.swing.GroupLayout headlinePanelLayout = new javax.swing.GroupLayout(headlinePanel);
        headlinePanel.setLayout(headlinePanelLayout);
        headlinePanelLayout.setHorizontalGroup(
            headlinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headlinePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jLabel3)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        headlinePanelLayout.setVerticalGroup(
            headlinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headlinePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(headlinePanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gymequipments/resources/running.png"))); // NOI18N

        textUserName.setBackground(new java.awt.Color(232, 232, 232));
        textUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textUserName.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(112, 88, 124), 1, true), "Username", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(112, 88, 124))); // NOI18N

        textPasscode.setBackground(new java.awt.Color(232, 232, 232));
        textPasscode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textPasscode.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(112, 88, 124), 1, true), "Password", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(112, 88, 124))); // NOI18N

        loginButton.setText("LOGIN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headlinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(loginImage, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textUserName)
                    .addComponent(textPasscode)
                    .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addComponent(headlinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(textUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(textPasscode, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(loginImage, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String pass = new String(textPasscode.getPassword());
        if(textUserName.getText().isEmpty() || pass.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please Fill all the fields below");
        }
        else if (textUserName.getText().equals("admin") && pass.equals("admin")){
            showPanels("mainPanel");
        }
        else{
            JOptionPane.showMessageDialog(this,"Username or Password Wrong");
        }
        

        // Check if username or password is empty
        

        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void adminButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminButtonMouseClicked
        showNewPanels("adminpanel");        // TODO add your handling code here:
    }//GEN-LAST:event_adminButtonMouseClicked

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        showNewPanels("homepanel");
    }//GEN-LAST:event_homeButtonMouseClicked

    private void aboutusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutusButtonMouseClicked
        showNewPanels("aboutuspanel");
    }//GEN-LAST:event_aboutusButtonMouseClicked

    private void addbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbuttonMouseClicked
               // TODO add your handling code here:
               String Id, name, weight, brand, category, use, modelno;
Id = IdTextField.getText();
name = nameTextField.getText();
weight = weightTextField.getText();
brand = BrandTextField.getText();
category = categoryField.getText();
use = UseTextField.getText();
modelno = modelNoTextfield.getText();

// Check if any fields are empty
if (Validate.isNullorEmpty(name) || Validate.isNullorEmpty(Id) || Validate.isNullorEmpty(weight) 
    || Validate.isNullorEmpty(brand) || Validate.isNullorEmpty(category) || Validate.isNullorEmpty(use) 
    || Validate.isNullorEmpty(modelno)) {
    
    JOptionPane.showMessageDialog(this, "Please fill all the fields", "INFORMATION", JOptionPane.ERROR_MESSAGE);
} else { 
    boolean valid = true;

    // Validate individual fields
    if (!Validate.isValidName(name)) {
        JOptionPane.showMessageDialog(this, "Name must be filled", "INFORMATION", JOptionPane.ERROR_MESSAGE);
        valid = false;
    }
    if (!Validate.isValidID(Id)) {
        JOptionPane.showMessageDialog(this, "ID must be in this format 'KTM 1234'", "INFORMATION", JOptionPane.ERROR_MESSAGE);
        valid = false;
    }
    if (!Validate.isValidUSE(use)) {
        JOptionPane.showMessageDialog(this, "Fill the use field", "INFORMATION", JOptionPane.ERROR_MESSAGE);
        valid = false;
    }
    if (!Validate.isValidCATEGORY(category)) {
        JOptionPane.showMessageDialog(this, "Fill the category field", "INFORMATION", JOptionPane.ERROR_MESSAGE);
        valid = false;
    }
    if (!Validate.isValidMODELNO(modelno)) {
        JOptionPane.showMessageDialog(this, "Model number should be in this pattern 'PATS66'", "INFORMATION", JOptionPane.ERROR_MESSAGE);
        valid = false;
    }

    // Proceed only if all fields are valid
    if (valid) {
        // Check for duplicate ID
        boolean isDuplicate = false;

        for (gymequippmentsmodel equipment : euiplist) {
            if (equipment.getID().equalsIgnoreCase(Id)) {
                isDuplicate = true;
                break;
            }
        }

        if (isDuplicate) {
            // Show error message if duplicate ID is found
            JOptionPane.showMessageDialog(this, "Duplicate ID detected! The equipment with this ID already exists.", "INFORMATION", JOptionPane.ERROR_MESSAGE);
        } else {
            // Add the new equipment if ID is not duplicate
            gymequippmentsmodel gymequippment = new gymequippmentsmodel(Id, name, weight, brand, category, modelno, use);
            registergymequip(gymequippment);
            euiplist.add(gymequippment);

            JOptionPane.showMessageDialog(this, "Successfully added!", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
        }
    }
}

         // JOptionPane.showMessageDialog(this,"Sucessfully added"); 
          
    }//GEN-LAST:event_addbuttonMouseClicked

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addbuttonActionPerformed

    private void IdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdTextFieldActionPerformed

    private void weightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        showPanels("loginPanel");
    }//GEN-LAST:event_jButton2MouseClicked

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminButtonActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        IdTextField.setText("");
        weightTextField.setText("");
        BrandTextField.setText("");
        modelNoTextfield.setText("");
        UseTextField.setText("");
        nameTextField.setText("");
        categoryField.setText("");
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void modelNoTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNoTextfieldActionPerformed
        
    }//GEN-LAST:event_modelNoTextfieldActionPerformed

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        int row = tableGymEquipments.getSelectedRow();
        
        DefaultTableModel model = (DefaultTableModel)tableGymEquipments .getModel();
        model.removeRow(row);
        
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextFieldActionPerformed

    private void searchStudentLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchStudentLabelMouseClicked
     // Retrieve the search value entered by the user from a JTextField (assuming it's named SearchTextField)
    String searchValue = SearchTextField.getText().trim();  // Get the text from the search field

    // Check if the search value is empty
    if (searchValue.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter a name to search.", "Search Error", JOptionPane.ERROR_MESSAGE);
        return; // Stop further execution if the search field is empty
    }

    // Create a BinarySearch instance
    BinarySearch binarySearch = new BinarySearch();

    // Sort the list by name before performing the binary search
    binarySearch.sortByName(euiplist);  // Ensure the list is sorted by name

    // Call the binary search method to find the equipment by Name
    gymequippmentsmodel result = binarySearch.searchByName(searchValue, euiplist, 0, euiplist.size() - 1);

    // Check if a result is found
    if (result != null) {
        // Prepare a message with the equipment details
        String message = "ID: " + result.getID() + "\n" +
                         "Name: " + result.getName() + "\n" +
                         "Weight: " + result.getWeight() + "\n" +
                         "Brand: " + result.getBrand() + "\n" +
                         "Category: " + result.getCategory() + "\n" +
                         "Model: " + result.getModel() + "\n" +
                         "Use: " + result.getUse();

        // Show the result in a JOptionPane
        JOptionPane.showMessageDialog(null, message, "Search Result", JOptionPane.INFORMATION_MESSAGE);
    } else {
        // If no result is found, show an error message
        JOptionPane.showMessageDialog(null, "No equipment found with Name: " + searchValue,
                                      "Search Result", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_searchStudentLabelMouseClicked

    private void sortdropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortdropdownActionPerformed
        //TODO add your handling code here:
        String selectedoption = (String) sortdropdown.getSelectedItem();
    SelectionSort selectionSort = new SelectionSort();
    InsertionSort insertionSort = new InsertionSort();
    MergeSort mergeSort = new MergeSort();
    
    switch (selectedoption.trim()) {
        case "Name":
            selectionSort.performSelectionSort(euiplist);
            break;

        case "ID":
            insertionSort.performInsertionSort(euiplist);
            break;

        case "Weight":
            mergeSort.performMergeSort(euiplist, 0, euiplist.size() - 1);
            break;

        default:
            break;
    }
    
    DefaultTableModel gymTableModel = (DefaultTableModel) tableGymEquipments.getModel();
    gymTableModel.setRowCount(0);
    System.out.print(euiplist);

    euiplist.forEach(element -> {
        Object[] gymdata = {
            element.getID(),
            element.getName(),
            element.getWeight(),
            element.getBrand(),
            element.getCategory(),
            element.getModel(),
            element.getUse()
        };

        // Debugging output to check Contract Value
        System.out.println("GYM EQUIPMENT NAME: " + element.getName());

        // Add data to the table model
        gymTableModel.addRow(gymdata);
    });
    }//GEN-LAST:event_sortdropdownActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gymequippmentsIs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gymequippmentsIs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gymequippmentsIs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gymequippmentsIs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gymequippmentsIs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BrandTextField;
    private javax.swing.JTextField IdTextField;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JTextField UseTextField;
    private javax.swing.JPanel VariablesPanel;
    private javax.swing.JPanel aboutUsHeadPanel;
    private javax.swing.JPanel aboutUsPanel;
    private javax.swing.JLabel aboutUslabel;
    private javax.swing.JButton aboutusButton;
    private javax.swing.JPanel aboutusfotterPanel;
    private javax.swing.JButton addbutton;
    private javax.swing.JButton adminButton;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JPanel anoutUsMidPanel;
    private javax.swing.JLabel brandlabel;
    private javax.swing.JLabel callIconLabel;
    private javax.swing.JTextField categoryField;
    private javax.swing.JLabel categorylabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel dropdownpanel;
    private javax.swing.JLabel fabebooklogo;
    private javax.swing.JPanel headlinePanel;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel homePageMidPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel homelabel;
    private javax.swing.JPanel homemidPanel;
    private javax.swing.JPanel hometitlepanel;
    private javax.swing.JLabel idlabel;
    private javax.swing.JLabel image1Panel;
    private javax.swing.JLabel image1Text;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel image2Text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labellogo;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginImage;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel mailAdressicon;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField modelNoTextfield;
    private javax.swing.JLabel modelNolabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel namelabel;
    private javax.swing.JScrollPane scrollPanelTable;
    private javax.swing.JLabel searchStudentLabel;
    private javax.swing.JPanel searchpanel;
    private javax.swing.JLabel shortbytextfield;
    private javax.swing.JComboBox<String> sortdropdown;
    private javax.swing.JTable tableGymEquipments;
    private javax.swing.JPasswordField textPasscode;
    private javax.swing.JTextField textUserName;
    private javax.swing.JLabel twitterlogo;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel useLabel;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JTextField weightTextField;
    // End of variables declaration//GEN-END:variables
}
